name: pytorch_radon
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - carterbox-torch-radon=3.0.0
  - cpython=3.13.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=9.3.0.75
  - filelock=3.16.1
  - freetype=2.12.1
  - fsspec=2024.10.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - jinja2=3.1.4
  - kernel-headers_linux-64=3.10.0
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.23
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libmagma=2.8.0
  - libmagma_sparse=2.8.0
  - libmpdec=4.0.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libopenblas=0.3.28
  - libpng=1.6.44
  - libprotobuf=5.28.2
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuuid=2.38.1
  - libuv=1.49.2
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - llvm-openmp=19.1.5
  - markupsafe=3.0.2
  - mkl=2024.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nccl=2.23.4.1
  - ncurses=6.5
  - networkx=3.4.2
  - numpy=2.2.0
  - openjpeg=2.5.3
  - openssl=3.4.0
  - pillow=11.0.0
  - pip=24.3.1
  - pthread-stubs=0.4
  - python=3.13.1
  - python_abi=3.13
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - readline=8.2
  - scipy=1.14.1
  - setuptools=75.6.0
  - sleef=3.7
  - sympy=1.13.3
  - sysroot_linux-64=2.17
  - tbb=2021.13.0
  - tk=8.6.13
  - torchvision=0.20.1
  - typing_extensions=4.12.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.0
      - click==8.1.7
      - contourpy==1.3.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - dxchange==0.0.1
      - fastcore==1.7.27
      - fonttools==4.55.3
      - gitdb==4.0.11
      - gitpython==3.1.43
      - idna==3.10
      - imageio==2.36.1
      - iniconfig==2.0.0
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - lazy-loader==0.4
      - matplotlib==3.10.0
      - nibabel==5.3.2
      - packaging==24.2
      - pandas==2.2.3
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - protobuf==5.29.1
      - psutil==6.1.0
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pyparsing==3.2.0
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.3
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - scikit-image==0.25.0
      - scikit-learn==1.6.0
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - six==1.17.0
      - smmap==5.0.1
      - threadpoolctl==3.5.0
      - tifffile==2024.12.12
      - torchsummary==1.5.1
      - torchviz==0.0.3
      - tqdm==4.67.1
      - tzdata==2024.2
      - urllib3==2.2.3
      - wandb==0.19.1
